name: Python Microservices CI

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip install -r user-service/requirements.txt
          pip install -r order-service/requirements.txt
          pip install pytest httpx

      - name: Run User Service tests
        run: |
          cd user-service
          pytest

      - name: Run Order Service tests
        run: |
          cd order-service
          pytest

      - name: Build User Service Docker image
        run: docker build -t user-service:ci ./user-service

      - name: Build Order Service Docker image
        run: docker build -t order-service:ci ./order-service

      - name: Scan User Service image
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: user-service:ci
          format: table
          exit-code: '1'
          ignore-unfixed: true
          severity: CRITICAL,HIGH

      - name: Scan Order Service image
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: order-service:ci
          format: table
          exit-code: '1'
          ignore-unfixed: true
          severity: CRITICAL,HIGH
